# Brainstorming and Focus Group Quantitative Experimentation 2.1:**Difficult people** under **action correction** + **divergence intervention**

Can we use TinyTroupe to brainstorm product ideas?

In [1]:
import sys

from pprint import pprint

from tinytroupe import config_manager
from tinytroupe.agent import TinyPerson
from tinytroupe.environment import TinyWorld
from tinytroupe.experimentation import InPlaceExperimentRunner
from tinytroupe.steering import Intervention
from tinytroupe.examples import *
from tinytroupe.validation import propositions
from tinytroupe.extraction import ResultsExtractor
from tinytroupe.utils.parallel import parallel_map_dict, parallel_map_cross
from tinytroupe.validation import hard_persona_adherence, persona_adherence, self_consistency, fluency, task_completion, divergence

# specific utilities
from common_utils import *

!!!!
DISCLAIMER: TinyTroupe relies on Artificial Intelligence (AI) models to generate content.
The AI models are not perfect and may produce inappropriate or inaccurate results.
For any serious or consequential use, please review the generated content before using it.
!!!!

Looking for default config on: C:\Users\pdasilva\repos\TinyTroupe and personal repos\TinyTroupe\tinytroupe\utils\..\config.ini
Found custom config on: c:\Users\pdasilva\repos\TinyTroupe and personal repos\TinyTroupe\publications\paper_artifacts_april-2026\config.ini
TinyTroupe version: 0.8.0
Current date and time (local): 2026-05-05 23:14:52
Current date and time (UTC):   2026-05-06 02:14:52

=================================
Current TinyTroupe configuration
=================================
[OpenAI]
api_type = azure
azure_api_version = 2024-12-01-preview
model = gpt-5-mini
reasoning_model = o3-mini
vision_detail = auto
embedding_model = text-embedding-3-small
azure_embedding_model_api_version = 2023-05-15
max_completion_tokens = 128000
timeout = 300
max_attempts = 5
waiting_time = 5
exponential_backoff_factor = 5
max_concurrent_model_calls = 4
reasoning_effort = high
cache_api_calls = False
cache_file_name = openai_api_cache.pickle
max_content_display_length = 1024

[Simulation]
parallel_agent_generation = True
parallel_agent_actions = True
rai_harmful_content_prevention = True
rai_copyright_infringement_prevention = True

[Cognition]
enable_memory_consolidation = False
enable_continuous_contextual_semantic_memory_retrieval = False
min_episode_length = 10
max_episode_length = 15
episodic_memory_fixed_prefix_length = 10
episodic_memory_lookback_length = 20

[ActionGenerator]
max_attempts = 2
enable_quality_checks = False
enable_regeneration = True
enable_direct_correction = False
enable_quality_check_for_persona_adherence = True
enable_quality_check_for_selfconsistency = False
enable_quality_check_for_fluency = False
enable_quality_check_for_suitability = False
enable_quality_check_for_similarity = False
continue_on_failure = True
quality_threshold = 5

[Logging]
loglevel = INFO
loglevel_console = INFO
loglevel_file = DEBUG
log_include_thread_id = True

2026-05-05 23:15:41,293 - MainThread(18496) - numexpr.utils - INFO - NumExpr defaulting to 8 threads.

In [2]:
#config_manager.update("loglevel", "WARNING")

## Parameters

In [3]:
full_mode = True  # set to True to run the full mode with all agents and tasks

# avoid displaying the communication, to make the output cleaner for eval
TinyPerson.communication_display = False

In [4]:
if full_mode:
    repetitions_per_task = 2
    simulation_steps = 5
    qty_agents = 12
    qty_proposals = 4

else:
    repetitions_per_task = 2
    simulation_steps = 5
    qty_agents = 4
    qty_proposals = 2

## Experiment setup

In [5]:
experiment_runner = InPlaceExperimentRunner("./brainstorming_and_focus_group_quantitative_experimentation_2.1.json")

experiment_runner.add_experiment("Control")
experiment_runner.add_experiment("Treatment")

2026-05-05 23:16:30,970 - MainThread(18496) - tinytroupe - WARNING - Configuration file './brainstorming_and_focus_group_quantitative_experimentation_2.1.json' exists and was loaded successfully. If you are trying to fully rerun the experiments, delete it first.
2026-05-05 23:16:30,983 - MainThread(18496) - tinytroupe - INFO - Experiment 'Control' already exists, nothihg to add.
2026-05-05 23:16:30,986 - MainThread(18496) - tinytroupe - INFO - Experiment 'Treatment' already exists, nothihg to add.
2026-05-05 23:16:30,983 - MainThread(18496) - tinytroupe - INFO - Experiment 'Control' already exists, nothihg to add.
2026-05-05 23:16:30,986 - MainThread(18496) - tinytroupe - INFO - Experiment 'Treatment' already exists, nothihg to add.

In [6]:
experiment_runner.activate_next_experiment()

#experiment_runner.fix_active_experiment("Control")
#experiment_runner.fix_active_experiment("Treatment")

2026-05-05 23:16:31,102 - MainThread(18496) - tinytroupe - INFO - All experiments have been finished. No more experiments to activate.

In [7]:
print(f"Running experiment {experiment_runner.get_active_experiment()}")

Running experiment None

## Agents and populations

In [8]:

people = []
if not experiment_runner.has_finished_all_experiments():
    # load agents
    people = TinyPerson.load_specifications_from_folder("./population/difficult_people_2")

    # filter to make it go faster?
    if qty_agents is not None:
        people = people[:qty_agents]

    # customize and print minibios 
    for person in people:
        person.import_fragment("./fragments/difficult_person.agent.fragment.json")
        print(person.minibio(extended=False))

In [9]:
len(people)

0

In [10]:
# divide people in several groups of 5
people_groups = []
for i in range(0, len(people), 4):
    people_groups.append(people[i:i+4]
    )

len(people_groups)

0

In [11]:
# The experiment refers to customers

if experiment_runner.get_active_experiment() == "Control":
    for person in people:
        person.action_generator.enable_reasoning_step = False
        person.action_generator.enable_quality_checks = False

elif experiment_runner.get_active_experiment() == "Treatment":    
    for person in people:
       person.action_generator.enable_reasoning_step = False
       person.action_generator.enable_quality_checks = True
       person.action_generator.max_attempts = 2
       person.action_generator.enable_regeneration = True
       person.action_generator.quality_threshold = 5

## Proposals

In [12]:
proposals = [
    {"theme": "Daily Life and Convenience",
     "objective": "Create ideas for products or services that simplify, enhance, or bring joy to everyday tasks, routines, and interactions."},

    {"theme": "Personal Growth and Wellbeing",
     "objective": "Generate concepts for products or experiences that support personal development, health, mental wellness, emotional care, or community connection."},

    {"theme": "Discovery and Exploration",
     "objective": "Explore ideas for products, services, or platforms that encourage curiosity, learning, adventure, and exploration of both the external world and inner self."},

    {"theme": "Productivity and Resourcefulness",
     "objective": "Invent new tools, processes, or organizational systems that empower people or groups to achieve more, optimize resources, or collaborate effectively."},

    {"theme": "Creativity and Expression",
     "objective": "Design ideas for new products, platforms, or services that inspire creativity, foster expression, enhance artistic skills, or enable new forms of storytelling and communication."}
]

if not full_mode:
    proposals = proposals[:qty_proposals]

In [13]:
# divide the proposals in exactly two groups (half/half)
proposals_groups = []
proposals_groups.append(proposals[:len(proposals)//2])
proposals_groups.append(proposals[len(proposals)//2:])

proposals_groups

[[{'theme': 'Daily Life and Convenience',
   'objective': 'Create ideas for products or services that simplify, enhance, or bring joy to everyday tasks, routines, and interactions.'},
  {'theme': 'Personal Growth and Wellbeing',
   'objective': 'Generate concepts for products or experiences that support personal development, health, mental wellness, emotional care, or community connection.'}],
 [{'theme': 'Discovery and Exploration',
   'objective': 'Explore ideas for products, services, or platforms that encourage curiosity, learning, adventure, and exploration of both the external world and inner self.'},
  {'theme': 'Productivity and Resourcefulness',
   'objective': 'Invent new tools, processes, or organizational systems that empower people or groups to achieve more, optimize resources, or collaborate effectively.'},
  {'theme': 'Creativity and Expression',
   'objective': 'Design ideas for new products, platforms, or services that inspire creativity, foster expression, enhance artistic skills, or enable new forms of storytelling and communication.'}]]

## Auxiliary functions

In [14]:
def brainstorming_battery(agents, proposals, interventions, agent_propositions, environment_propositions, 
                          repetitions = 5, simulation_steps=10): 
    
    agent_propositions_scores = {}
    environment_propositions_scores = {}

    experiments_count = 0
    total_expected_experiments = len(proposals) * repetitions #* len(agents)

    # loop over proposals and repetitions
    for proposal in proposals:

        objective = proposal["objective"]
        theme = proposal["theme"]

        for i in range(repetitions):
            print("\n############## STARTING A NEW RESEARCH SESSION #################")
            print(f"Overall experiment number: {experiments_count+1} / {total_expected_experiments}")
            print(f"Discussion objective: {objective}")
            print(f"Trial number: {i+1}")
            print(f"Agents: {agents}")

            # clear the episodic memory of all agents
            for person in agents:
                person.clear_episodic_memory()

            world = TinyWorld(agents=agents, interventions=interventions)
            
            # Participants introduce themselves
            world.broadcast(f"""
                Hello everyone! Let's start by introducing ourselves, and mentioning problems we face in our daily personal
                and professional lives related to the following theme: {theme}
                
                Please:
                  - present yourself and your background;
                  - present some key personal problems related to the theme;
                  - present some key problems related to the theme that you face in your work;
                  - present some key problems related to the theme that you see in your industry as a whole.
                  
                Don't discuss solutions yet, just the problems you face and see others facing.
                """)
            world.run(1)
            
            # now to the brainstorming session itself
            world.broadcast(f"""
                Folks, your mission is to brainstorm {objective}. 
                Please follow these guidelines:
                  - give a unique and informative name to each idea you propose, so that it is easy to refer to it. Say it like "Idea name: '<name of the idea>'".;
                  - explain why you think it is a good idea, and what problem it solves, and how you feel about it;
                  - your ideas should be new complete, self-contained, products or services, not features for other existing products or services;
                  - think of creative ideas that would somehow help you in both in your personal and professional lives.
                  - create as many different and unique ideas as you can during the brainstorming session. Each idea must be **completely** different from the others 
                    (either by yourself or by others), and not just a variation of an existing idea.
                  - you should criticize each other's ideas, in order to make sure they are as
                    good as possible, but no more than once per idea.
                  - you should also provide suggestions for improvement to each other's ideas, in order to make them as good as possible, 
                    but no more than once per idea.
                  - regardless of critique or complement, you **must** primarily propose new ideas quickly, 
                    not just build on existing ones. 
                  - propose one idea at a time, instead of proposing multiple ideas at once, to allow appropriate discussion.
                  - you should **not** propose ideas that are too similar to each other, or to the ones already proposed by others.
                  - before saying anything, THINK deeply about yourself, your beliefs, interests, needs, life, etc., to come up with ideas that are
                    truly unique and different from the ones already proposed by others.
                   
                Please start the discussion now.
                """)
            world.run(simulation_steps)

            # extract and count ideas
            rapporteur = agents[0]  # the first agent is the rapporteur
            rapporteur.listen_and_act("Can you please consolidate the ideas that the group came up with? Provide a lot of details on each idea, and complement anything missing.")
            ideas = ResultsExtractor().extract_results_from_agent(rapporteur, 
                                    extraction_objective="Consolidates the ideas that the group came up with, explaining each idea as an item of a list." \
                                                        "Add information about: what problem the idea solves; to which target audience it is meant." \
                                                        "how is it different from competing, existing, products.", 
                                    situation="A focus group to brainstorm new product ideas.",
                                    fields= ["name", "description", "problem", "target_audience", "competition_analysis"],
                                    fields_hints={"ideas": "must be the root of the resulting dictionary."},)
            pprint(ideas)
            if "ideas_qty" not in environment_propositions_scores:
                environment_propositions_scores["ideas_qty"] = []
            if ideas is not None and "ideas" in ideas and isinstance(ideas["ideas"], list):
                environment_propositions_scores["ideas_qty"].append(len(ideas["ideas"]))

            # Evaluate environment propositions in parallel
            env_results = parallel_map_dict(
                environment_propositions,
                lambda item: item[1].copy().score(
                    world, 
                    claim_variables={"task_description": f"A brainstorming or focus group session was run about: {objective}."}, 
                    return_full_response=True
                )
            )
            
            # Process environment results
            for k, result in env_results.items():
                if k not in environment_propositions_scores:
                    environment_propositions_scores[k] = []
                environment_propositions_scores[k].append(result["value"])
                print("value: ", result["value"])
                print("justification: ", result["justification"])
                print("reasoning: ", result["reasoning"])

            # Evaluate agent propositions across all agents in parallel
            agent_results = parallel_map_cross(
                [agents, agent_propositions.items()],
                lambda agent, prop_item: (
                    prop_item[0],  # proposition key
                    prop_item[1].copy().score(agent, return_full_response=True)  # result
                )
            )
            
            # Process agent results
            for k, result in agent_results:
                if k not in agent_propositions_scores:
                    agent_propositions_scores[k] = []
                if result is not None:
                    agent_propositions_scores[k].append(result["value"])
                    print("value: ", result["value"])
                    print("justification: ", result["justification"])
                    print("reasoning: ", result["reasoning"])
                    print("\n\n")
                else:
                    print(f"*****WARNING:***** Agent did not respond to proposition {k}.")
            #
            ##for k, proposition in agent_propositions.items():
            ##    for person in world.agents:
            ##        result = proposition.copy().score(person, return_full_response=True)
            ##        
            ##        if k not in agent_propositions_scores:
            ##            agent_propositions_scores[k] = []
            ##        agent_propositions_scores[k].append(result["value"])
            ##
            ##        print("value: ", result["value"])
            ##        print("justification: ", result["justification"])
            ##        print("reasoning: ", result["reasoning"])
            ##        print("\n\n")
            ##
            
            experiments_count += 1
            print("\n\n")

    return agent_propositions_scores, environment_propositions_scores

## Perform experiment

In [15]:
agent_propositions_scores={}
environment_propositions_scores={}

In [16]:
def brainstorm(people, proposals=proposals):
    global agent_propositions_scores, environment_propositions_scores
    if not experiment_runner.has_finished_all_experiments():

        interventions = []
        if experiment_runner.get_active_experiment() == "Treatment":
            interventions = \
                Intervention.create_for_each(people)\
                    .set_functional_precondition(lambda target: target.actions_count >=7)\
                    .set_textual_precondition(
                        """
                        AGENT IS NOT PROPOSING COMPLETELY NEW PRODUCT/SERVICE IDEAS ANYMORE:
                        The last **entirely** new product/service idea proposed by this agent, if any, was proposed by him/her **more** than 5 of simulation events ago.
                        That is to say, the agent has not proposed any new product/service idea in the last 5 of his/her simulation trajectory events.
                        Additional features, variations of or other refinements to product/service ideas already proposed are NOT considered new!

                        How to compute the steps gap:
                        1. Determine the current next event number (N); and the last event number in which the agent proposed a new product/service idea (M).
                            This information can be found in the simulation trajectory.
                        2. Compute the **difference** beteween the current next event number and the last event number in which the agent proposed a new product/service idea: D = N - M
                        3. The proposition is true if, and only if, the difference D is **greater than** 5.
                        """)\
                    .set_effect(lambda target: target.think("""
                                                            I need to propose additional, **completelly** new and different, product/service ideas. This was part of the requirement for this session.
                                                            I will propose an entirely **new** idea now, I **cannot** repeat or refine previous ideas! I cannot make variations
                                                            of previous ideas (e.g., "XYZ for A", "XYZ for B", "XYZ for Z" are repetitive, there should be only one "XYZ"), 
                                                            I need to think of something **entirely** new and different.
                                                            To help me avoid repeating previous ideas, I'll now explicitly THINK about all the ideas already given by myself or
                                                            others, and then, based on that, I'll think again about a new unique idea.
                                                            """))

                                                            
        tmp_agent_propositions_scores, tmp_environment_propositions_scores = \
            brainstorming_battery(
                agents=people,
                proposals=proposals,
                interventions=interventions,    
                agent_propositions={
                    "Hard Persona Adherence": hard_persona_adherence,
                    "Self-consistency": self_consistency,
                    "Fluency": fluency
                },
                environment_propositions={
                    "Task Completion": task_completion,
                    "Divergence": divergence
                },
                repetitions=repetitions_per_task,
                simulation_steps=simulation_steps
            )

        pprint("NEW AGENT PROPOSITIONS SCORES")
        pprint(tmp_agent_propositions_scores)
        print("\n\n")
        pprint("NEW ENVIRONMENT PROPOSITIONS SCORES")
        pprint(tmp_environment_propositions_scores)

        # merge the scores lists
        agent_propositions_scores = merge_dicts_of_lists(tmp_agent_propositions_scores, agent_propositions_scores)
        environment_propositions_scores = merge_dicts_of_lists(tmp_environment_propositions_scores, environment_propositions_scores)

        return agent_propositions_scores, environment_propositions_scores

In [17]:
brainstorm(people_groups[0], proposals_groups[0]) if len(people_groups) > 0  and len(proposals_groups) > 0 else None

In [18]:
brainstorm(people_groups[0], proposals_groups[1]) if len(people_groups) > 0  and len(proposals_groups) > 1 else None

In [19]:
brainstorm(people_groups[1], proposals_groups[0]) if len(people_groups) > 1  and len(proposals_groups) > 0 else None

In [20]:
brainstorm(people_groups[1], proposals_groups[1]) if len(people_groups) > 1  and len(proposals_groups) > 1 else None

In [21]:
brainstorm(people_groups[2], proposals_groups[0]) if len(people_groups) > 2  and len(proposals_groups) > 0 else None

In [22]:
brainstorm(people_groups[2], proposals_groups[1]) if len(people_groups) > 2  and len(proposals_groups) > 1 else None

In [23]:
brainstorm(people_groups[3], proposals_groups[0]) if len(people_groups) > 3  and len(proposals_groups) > 0 else None

In [24]:
brainstorm(people_groups[3], proposals_groups[1]) if len(people_groups) > 3  and len(proposals_groups) > 1 else None

In [25]:
brainstorm(people_groups[4], proposals_groups[0]) if len(people_groups) > 4  and len(proposals_groups) > 0 else None

In [26]:
brainstorm(people_groups[4], proposals_groups[1]) if len(people_groups) > 4  and len(proposals_groups) > 1 else None

## Extract results and analyze

In [27]:
if experiment_runner.get_active_experiment() in ["Control", "Treatment"]:
    combined_scores = {**agent_propositions_scores, **environment_propositions_scores}
    experiment_runner.add_experiment_results(combined_scores, experiment_name=experiment_runner.get_active_experiment()) 
    
    plot_scores(combined_scores)

else:
    print("Experiment finished. No more experiments to run.")

Experiment finished. No more experiments to run.

In [28]:
if experiment_runner.has_finished_all_experiments():
    print("All experiments have been finished.")
    print(f"STATISTICTS: Control vs")
    pprint(experiment_runner.run_statistical_tests(control_experiment_name='Control'))

    # plot scores of both experiments
    experiment_control_scores = experiment_runner.get_experiment_results("Control")
    experiment_treatment_scores = experiment_runner.get_experiment_results("Treatment")
    
    
    plot_scores(experiment_control_scores)
    plot_scores(experiment_treatment_scores)

else:
    print("Not all experiments have been finished. RESTART AND RERUN.")

All experiments have been finished.
STATISTICTS: Control vs
{'Treatment': {'Divergence': {'confidence_interval': (2.9781326893612707,
                                                      5.155200643972064),
                              'confidence_level': 0.95,
                              'control_mean': 0.6,
                              'control_sample_size': 30,
                              'control_std': 1.132589343358684,
                              'degrees_of_freedom': 38.757901017288404,
                              'effect_size': 1.9514940230059967,
                              'mean_difference': 4.066666666666667,
                              'p_value': 3.864990185259835e-09,
                              'percent_change': 677.7777777777779,
                              'significant': True,
                              't_statistic': -7.558103851325538,
                              'test_type': 'Welch t-test (unequal variance)',
                              'treatment_mean': 4.666666666666667,
                              'treatment_sample_size': 30,
                              'treatment_std': 2.7207166060754493},
               'Fluency': {'confidence_interval': (-3.151590250364192,
                                                   -2.381743082969141),
                           'confidence_level': 0.95,
                           'control_mean': 8.025,
                           'control_sample_size': 120,
                           'control_std': 0.7271736468031842,
                           'degrees_of_freedom': 149.7355584463547,
                           'effect_size': -1.8334921808732336,
                           'mean_difference': -2.7666666666666666,
                           'p_value': 1.5552722449314418e-29,
                           'percent_change': -34.47559709241952,
                           'significant': True,
                           't_statistic': 14.2021693638471,
                           'test_type': 'Welch t-test (unequal variance)',
                           'treatment_mean': 5.258333333333334,
                           'treatment_sample_size': 120,
                           'treatment_std': 2.0062751695673278},
               'Hard Persona Adherence': {'confidence_interval': (0.7652266030272584,
                                                                  1.7013000076169993),
                                          'confidence_level': 0.95,
                                          'control_mean': 1.7583333333333333,
                                          'control_sample_size': 120,
                                          'control_std': 1.5824448340024573,
                                          'degrees_of_freedom': 221.52819687177467,
                                          'effect_size': 0.6725202751710837,
                                          'mean_difference': 1.233263305322129,
                                          'p_value': 4.6846856491444453e-07,
                                          'percent_change': 70.13819745907843,
                                          'significant': True,
                                          't_statistic': -5.192818158210111,
                                          'test_type': 'Welch t-test (unequal '
                                                       'variance)',
                                          'treatment_mean': 2.991596638655462,
                                          'treatment_sample_size': 119,
                                          'treatment_std': 2.056390610850814},
               'Self-consistency': {'confidence_interval': (-5.775032234749649,
                                                            -4.574967765250352),
                                    'confidence_level': 0.95,
                                    'control_mean': 8.683333333333334,
                                    'control_sample_size': 120,
                                    'control_std': 1.2634708320406003,
                                    'degrees_of_freedom': 157.9764497278647,
                                    'effect_size': -2.199115261211184,
                                    'mean_difference': -5.175000000000001,
                                    'p_value': 1.339973101259657e-37,
                                    'percent_change': -59.59692898272554,
                                    'significant': True,
                                    't_statistic': 17.03427356612298,
                                    'test_type': 'Welch t-test (unequal '
                                                 'variance)',
                                    'treatment_mean': 3.5083333333333333,
                                    'treatment_sample_size': 120,
                                    'treatment_std': 3.078785729573829},
               'Task Completion': {'confidence_interval': (-4.334376860433869,
                                                           -1.9989564728994649),
                                   'confidence_level': 0.95,
                                   'control_mean': 8.966666666666667,
                                   'control_sample_size': 30,
                                   'control_std': 0.18257418583505536,
                                   'degrees_of_freedom': 29.198253223432353,
                                   'effect_size': -1.4316460455645899,
                                   'mean_difference': -3.166666666666667,
                                   'p_value': 5.46640822668017e-06,
                                   'percent_change': -35.31598513011153,
                                   'significant': True,
                                   't_statistic': 5.544741292135361,
                                   'test_type': 'Welch t-test (unequal '
                                                'variance)',
                                   'treatment_mean': 5.8,
                                   'treatment_sample_size': 30,
                                   'treatment_std': 3.122775070018818},
               'ideas_qty': {'confidence_interval': (0.4112637224972642,
                                                     1.9358627142843452),
                             'confidence_level': 0.95,
                             'control_mean': 3.793103448275862,
                             'control_sample_size': 29,
                             'control_std': 0.5592923044110288,
                             'degrees_of_freedom': 33.776820792178164,
                             'effect_size': 0.8030702046091801,
                             'mean_difference': 1.1735632183908047,
                             'p_value': 0.0035991064140555406,
                             'percent_change': 30.939393939393938,
                             'significant': True,
                             't_statistic': -3.129410432814284,
                             'test_type': 'Welch t-test (unequal variance)',
                             'treatment_mean': 4.966666666666667,
                             'treatment_sample_size': 30,
                             'treatment_std': 1.973677354293395}}}
{'Divergence': [2,
                0,
                0,
                1,
                0,
                0,
                0,
                1,
                1,
                0,
                3,
                0,
                0,
                0,
                0,
                2,
                0,
                5,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1],
 'Fluency': [7,
             7,
             9,
             8,
             7,
             6,
             9,
             9,
             9,
             6,
             8,
             9,
             8,
             8,
             9,
             8,
             8,
             9,
             8,
             9,
             6,
             8,
             8,
             9,
             8,
             9,
             8,
             8,
             6,
             8,
             9,
             9,
             7,
             8,
             9,
             9,
             9,
             9,
             8,
             8,
             7,
             7,
             8,
             9,
             8,
             8,
             8,
             8,
             8,
             8,
             8,
             8,
             9,
             8,
             8,
             8,
             8,
             7,
             9,
             8,
             9,
             8,
             8,
             8,
             8,
             7,
             8,
             7,
             7,
             8,
             8,
             7,
             8,
             7,
             9,
             9,
             7,
             8,
             9,
             7,
             8,
             8,
             8,
             8,
             8,
             9,
             8,
             9,
             8,
             8,
             8,
             8,
             8,
             8,
             8,
             9,
             7,
             7,
             8,
             8,
             8,
             8,
             8,
             8,
             8,
             8,
             9,
             9,
             8,
             8,
             8,
             9,
             8,
             8,
             7,
             8,
             8,
             7,
             8,
             8],
 'Hard Persona Adherence': [0,
                            0,
                            2,
                            0,
                            0,
                            1,
                            4,
                            3,
                            3,
                            1,
                            0,
                            4,
                            2,
                            5,
                            0,
                            0,
                            3,
                            1,
                            2,
                            0,
                            0,
                            5,
                            3,
                            2,
                            3,
                            1,
                            0,
                            1,
                            3,
                            5,
                            3,
                            0,
                            1,
                            2,
                            1,
                            5,
                            2,
                            2,
                            2,
                            3,
                            1,
                            0,
                            3,
                            3,
                            0,
                            0,
                            2,
                            1,
                            3,
                            0,
                            5,
                            3,
                            3,
                            3,
                            2,
                            0,
                            3,
                            3,
                            0,
                            0,
                            2,
                            0,
                            0,
                            0,
                            2,
                            1,
                            3,
                            2,
                            2,
                            2,
                            0,
                            4,
                            0,
                            0,
                            0,
                            2,
                            0,
                            0,
                            3,
                            1,
                            2,
                            1,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1,
                            2,
                            1,
                            2,
                            0,
                            1,
                            4,
                            3,
                            0,
                            5,
                            3,
                            0,
                            1,
                            2,
                            1,
                            0,
                            3,
                            2,
                            0,
                            2,
                            3,
                            1,
                            9,
                            0,
                            3,
                            2,
                            1,
                            4,
                            1,
                            3,
                            1,
                            2,
                            3],
 'Self-consistency': [9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      3,
                      9,
                      9,
                      9,
                      9,
                      9,
                      2,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      8,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      8,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      2,
                      9,
                      9,
                      9,
                      9,
                      9,
                      7,
                      8,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      7,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      7,
                      9,
                      9,
                      9,
                      2,
                      9,
                      9,
                      9,
                      9,
                      7,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9,
                      9],
 'Task Completion': [9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     9,
                     8,
                     9,
                     9,
                     9,
                     9],
 'ideas_qty': [4,
               4,
               4,
               4,
               4,
               4,
               4,
               5,
               4,
               4,
               4,
               4,
               4,
               4,
               4,
               2,
               4,
               4,
               3,
               4,
               3,
               3,
               4,
               3,
               4,
               4,
               4,
               4,
               3]}

              Proposition  Average Score  Standard Deviation  Count
0  Hard Persona Adherence       1.758333            1.582445  120.0
1        Self-consistency       8.683333            1.263471  120.0
2                 Fluency       8.025000            0.727174  120.0
3               ideas_qty       3.793103            0.559292   29.0
4         Task Completion       8.966667            0.182574   30.0
5              Divergence       0.600000            1.132589   30.0

{'Divergence': [7,
                8,
                6,
                8,
                6,
                2,
                7,
                8,
                5,
                8,
                2,
                4,
                1,
                7,
                2,
                7,
                7,
                9,
                1,
                1,
                2,
                1,
                3,
                5,
                3,
                4,
                3,
                7,
                0,
                6],
 'Fluency': [7,
             8,
             8,
             6,
             6,
             8,
             6,
             0,
             7,
             4,
             5,
             1,
             6,
             6,
             7,
             4,
             7,
             4,
             7,
             7,
             6,
             7,
             7,
             5,
             8,
             6,
             4,
             6,
             0,
             0,
             7,
             4,
             8,
             6,
             1,
             7,
             2,
             2,
             7,
             5,
             8,
             8,
             6,
             8,
             4,
             3,
             4,
             5,
             2,
             5,
             2,
             6,
             6,
             2,
             4,
             8,
             7,
             1,
             4,
             6,
             8,
             5,
             5,
             7,
             4,
             3,
             4,
             7,
             8,
             6,
             4,
             7,
             6,
             6,
             3,
             2,
             6,
             2,
             5,
             6,
             8,
             7,
             6,
             7,
             4,
             3,
             7,
             6,
             4,
             2,
             4,
             5,
             6,
             7,
             6,
             7,
             7,
             5,
             6,
             6,
             5,
             6,
             4,
             3,
             7,
             6,
             7,
             4,
             4,
             7,
             3,
             5,
             7,
             5,
             2,
             6,
             4,
             7,
             6,
             5],
 'Hard Persona Adherence': [1,
                            4,
                            5,
                            4,
                            7,
                            2,
                            3,
                            9,
                            2,
                            3,
                            0,
                            6,
                            4,
                            5,
                            0,
                            3,
                            2,
                            5,
                            0,
                            0,
                            2,
                            4,
                            1,
                            4,
                            0,
                            2,
                            5,
                            1,
                            0,
                            1,
                            5,
                            1,
                            1,
                            5,
                            3,
                            1,
                            2,
                            1,
                            3,
                            2,
                            3,
                            7,
                            3,
                            1,
                            5,
                            7,
                            3,
                            5,
                            3,
                            3,
                            9,
                            2,
                            1,
                            5,
                            2,
                            2,
                            4,
                            7,
                            5,
                            1,
                            3,
                            2,
                            3,
                            3,
                            0,
                            1,
                            2,
                            0,
                            3,
                            2,
                            3,
                            1,
                            0,
                            5,
                            7,
                            0,
                            3,
                            3,
                            1,
                            4,
                            7,
                            0,
                            3,
                            3,
                            5,
                            7,
                            3,
                            3,
                            5,
                            2,
                            3,
                            3,
                            1,
                            1,
                            3,
                            1,
                            5,
                            3,
                            4,
                            1,
                            3,
                            2,
                            7,
                            2,
                            5,
                            2,
                            4,
                            3,
                            4,
                            0,
                            3,
                            4,
                            5,
                            1,
                            3,
                            5,
                            3,
                            0,
                            4],
 'Self-consistency': [2,
                      1,
                      6,
                      8,
                      3,
                      1,
                      2,
                      0,
                      0,
                      1,
                      0,
                      1,
                      1,
                      1,
                      1,
                      2,
                      6,
                      2,
                      2,
                      9,
                      3,
                      9,
                      7,
                      2,
                      9,
                      1,
                      2,
                      2,
                      2,
                      2,
                      9,
                      2,
                      1,
                      9,
                      8,
                      1,
                      2,
                      8,
                      2,
                      9,
                      2,
                      0,
                      1,
                      1,
                      1,
                      2,
                      2,
                      9,
                      2,
                      1,
                      7,
                      9,
                      3,
                      1,
                      9,
                      9,
                      1,
                      2,
                      9,
                      9,
                      1,
                      7,
                      4,
                      1,
                      2,
                      2,
                      2,
                      4,
                      8,
                      3,
                      1,
                      1,
                      0,
                      2,
                      7,
                      6,
                      1,
                      0,
                      7,
                      2,
                      8,
                      9,
                      1,
                      2,
                      1,
                      6,
                      0,
                      2,
                      2,
                      2,
                      3,
                      2,
                      2,
                      7,
                      1,
                      1,
                      2,
                      5,
                      1,
                      6,
                      6,
                      1,
                      6,
                      6,
                      9,
                      7,
                      1,
                      1,
                      0,
                      9,
                      1,
                      9,
                      2,
                      7,
                      6,
                      3,
                      0,
                      2,
                      0,
                      2],
 'Task Completion': [9,
                     0,
                     9,
                     5,
                     9,
                     5,
                     9,
                     8,
                     4,
                     8,
                     8,
                     7,
                     0,
                     7,
                     5,
                     8,
                     0,
                     9,
                     7,
                     7,
                     6,
                     4,
                     7,
                     9,
                     3,
                     2,
                     9,
                     8,
                     2,
                     0],
 'ideas_qty': [3,
               3,
               4,
               4,
               4,
               9,
               7,
               7,
               5,
               6,
               5,
               5,
               2,
               8,
               4,
               7,
               2,
               7,
               2,
               5,
               6,
               3,
               5,
               7,
               5,
               5,
               3,
               8,
               2,
               6]}

              Proposition  Average Score  Standard Deviation  Count
0  Hard Persona Adherence       2.991597            2.056391  119.0
1        Self-consistency       3.508333            3.078786  120.0
2                 Fluency       5.258333            2.006275  120.0
3               ideas_qty       4.966667            1.973677   30.0
4         Task Completion       5.800000            3.122775   30.0
5              Divergence       4.666667            2.720717   30.0

In [29]:
experiment_runner.finish_active_experiment()

2026-05-05 23:16:34,509 - MainThread(18496) - tinytroupe - INFO - No active experiment to finish.

False